### PR TITLE
Remove deprecated arguments from SN model initialisers

### PR DESCRIPTION
**Pull request by JostMigenda**
This PR is intended to remove deprecations in the SN model initialisers, including initialising from a file name and inconsistent keyword arguments.

There are still a couple of `@deprecated` decorators we should remove before merging this. (E.g. for many models, the `eos` keyword is marked as deprecated, because there is only a single possible value; so it shouldn’t be required as part of the `__init__`.)
I think the best way to proceed there would be to remove `eos` from the parameter list and manually set `self.metadata["eos"]` in the `__init__` to the fixed value instead. I’ll do that tomorrow and mark this as a draft PR until then; but wanted to get it out now before I go to bed, in case you want to review this during your daytime, @Sheshuk. (Yay for timezones! 😉)

(Also: Yes, I’ve currently marked the branch from #353 as a base for this PR for simplicity; but can rebase it onto the `release_v2.0` branch tomorrow.)

### CODE REVIEW

**Review by Sheshuk — COMMENTED** [review]
Changes look good so far, and we're heading towards a cleaner and more beautiful future interface!
Looks like you've got everything, concerning with `legacy_filename_initialization`.

I agree with the plan to remove the deprecated parameters and putting them directly into the metadata.

**Comment by JostMigenda** [comment]
Ready for review now!

**Comment by JostMigenda** [comment]
Okay, now the integration tests are back to failing in `get_transformed_spectra` (where we expect them to fail until the flavour transformations are updated to three flavours) and it’s _actually_ ready to review.

**Review by sybenzvi — APPROVED** [review]
Changes are mostly removal of unused packages, options, and legacy interfaces. Looks good.

**Pull request merged**
