### PR TITLE
merge to/run/from_snowglobes into a single module

### LINKED ISSUE #82: Cleanup of {to,run,from}_snowglobes
(This is not a big deal in the grand scheme of things, but we should make these changes before we publish the ApJ paper; afterwards, changing the API to be different from what’s described in the paper will lead to user confusion.)

* The main function of `run_snowglobes` should be called `run` instead of `go`. (It seems confusing to me to use different verbs in the function name and module name; and of the two, _run_ is preferable because you don’t _go_ SNOwGLoBES, you _run_ SNOwGLoBES.
* Having separate arguments for the folder containing the tarfile and the tarfile itself is unnecessary. This should just be one argument; if the components are ever needed separately, `os.path.split` can easily do that.
* The go/run function needs a brief docstring, to help with #76.

I’ll try to work on this early next week; just wanted to write it down already so we don’t forget.

### PR DESCRIPTION
**Pull request by JostMigenda**
This merges `to_snowglobes`, `run_snowglobes` and `from_snowglobes` into a single module (`snewpy.snowglobes`). I’m leaving stubs in the original files to ensure existing code doesn’t break. Additional renaming and clean-up will come in a bit; once ready, this will fix #82.

Throughout, I will update `doc/nb/SNEWPY_examples.ipynb` to demonstrate the changes; and to verify that the output is unchanged.

### CODE REVIEW

**Comment by JostMigenda** [comment]
These commits
* add docstrings and some basic documentation (which helps with #76)
* simplify the API by having a single argument for the file path
* rename `go` to `simulate`.

I think it’s ready for review now, but I will add another commit later that updates all the demo notebooks.

**Comment by evanoconnor** [comment]
Hi, sorry for my silence.  I'm okay with this cleanup.

**Comment by evanoconnor** [comment]
A note about `snowglobes.generate_time_series()`.  It is quite different from `snowglobes.generate_fluence()` and they are not really swappable, they do different things.  We will need to clearly describe what each one is doing carefully.

**Comment by evanoconnor** [comment]
This can replace #55, but in the new snowglobes module format
This should resolve #90 as well

**Comment by evanoconnor** [comment]
This fixes the `SNEWS2.0_rate_table.py` script which was broken (#88)

**Comment by JostMigenda** [comment]
Thanks for the updates @evanoconnor!

My first commit cleans up some files that looked like they were added accidentally.
My second commit works with any input file extension, so we don’t have to remember to update the code if we e.g. add a new model with `.csv` (or `.txt` or …) input files. (The same for `generate_fluence`, while I was working on it.)

I’ll update `SNEWS2.0_rate_table.py` next, now that it should work.

**Comment by JostMigenda** [comment]
Updated `SNEWS2.0_rate_table.py`. I removed the KM3NeT entry for now, since sample scripts should work with the main branch of SNOwGLoBES. Once [the relevant PR](https://github.com/SNOwGLoBES/snowglobes/pull/10) is merged into SNOwGLoBES, we can re-add this.

**Comment by JostMigenda** [comment]
Modernized `TimeSeries.py`. In addition to merging the SNOwGLoBES-related modules, I’ve also verified that it works thanks to Evan’s earlier changes; so this fixes #88 as well.

It might still be better to merge it into `doc/nb/SNEWPY_examples.ipynb` instead and add explanations about the difference between `generate_fluence` and `generate_time_series`, but that’s beyond the scope of this PR.

**Pull request merged**
