### PR TITLE
Sheshuk/extras require docs fix

### LINKED ISSUE #133: Install documentation as 'extras' in setup.py
From discussion in #132:
`setup.py` has a mechanism called `extras_require` to handle optional dependencies. For example, we can define an extra named 'dev' which requires `numpydoc` and then `pip install snewpy[dev]` (or `pip install .[dev]`, if you’ve cloned the repo) will install `numpydoc`.
We could move documentation-specific dependencies to that mechanism, instead of having a separate `doc/requirements.txt` file and should also update the documentation in `contributing.rst` to mention these optional dependencies.

### PR DESCRIPTION
**Pull request by Sheshuk**
Closes #133

### CODE REVIEW

**Comment by Sheshuk** [comment]
Oh, now it's conflicting with the snowglobes_interface. I'll try to merge that

**Comment by JostMigenda** [comment]
This looks good to me; thanks!

Just want to check: Did you mean to target the `Sheshuk/snowglobes_interface` branch with this PR? It’s fairly unrelated to that one, so maybe targeting it at the `main` branch would be more appropriate?

**Review by JostMigenda — APPROVED** [review]

**Comment by Sheshuk** [comment]
Well, it interferes with the `dev` requirements you added in that target branch, So I decided to merge and resolve the conflicts here, instead of having conflicts merging to main.

**Comment by JostMigenda** [comment]
I’d prefer merging this into `main`, then merging `main` back into `Sheshuk/snowglobes_interface` and resolving conflicts on that branch. Otherwise, if we merge everything that conflicts with `Sheshuk/snowglobes_interface` into that branch instead of `main`, it becomes pretty unmanageable very quickly. But I guess for this small PR, it’s not a big deal.

**Pull request merged**
