### PR TITLE
Implementation of Quantum Decoherence in vacuum

### PR DESCRIPTION
**Pull request by santosmv**
The effects are combined with the MSW effect. In this case, the flavor conversion from quantum decoherence happens in vacuum (as in the MSC^e of [arXiv:2306.17591](https://arxiv.org/abs/2306.17591)), and no Earth matter effects are included in this version.

### CODE REVIEW

**Review by mcolomermolla — COMMENTED** [review]
I could use the QD class without problems in a FlavorTransformation notebook to build the flux and spectrum, which follows the expected trend from the paper. I did not find any issue with the flavor transition probabilities implementation, it follows the same scheme as for the other (i.e. AdiabaticSW). To me, this PR is good to go.

**Comment by JostMigenda** [comment]
Sorry for the delay! I just ran the unit tests (GitHub doesn't run them automatically for PRs from first-time contributors, I think) and unfortunately, these are currently failing; it looks like [some issue with units](https://github.com/SNEWS2/snewpy/actions/runs/6517988025/job/17703021180#step:6:1).  @santosmv, can you please take a look at this?

**Comment by santosmv** [comment]
Sure, I'll take a look at this.

**Comment by santosmv** [comment]
It was just missing units of quantum decoherence parameters in the `test_04_xforms.py`. Upon running this test, some issues were raised in the `assertEqual` methods, which were also fixed.

**Comment by JostMigenda** [comment]
Just added a minor edit to clean up some unnecessary unit conversions. (Usually, AstroPy handles those automatically as needed; manual conversions are mainly needed at the end to format for output.)

Otherwise, @mcolomermolla already posted an approving review above; so now that the test succeed, I’ll go ahead and merge. Many thanks @santosmv for your work and congratulations on your first SNEWPY PR! 🎉

**Review by JostMigenda — APPROVED** [review]

**Pull request merged**
